## Missing Values for ML - KNNImputer

In [3]:
import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer

In [4]:
my_df = pd.DataFrame({"A": [1,2,3,4,5],
                     "B": [1,1,3,3,4],
                     "C": [1,2,9,np.nan,20]})

In [5]:
knn_imputer = KNNImputer()

In [6]:
knn_imputer.fit_transform(my_df)

array([[ 1.,  1.,  1.],
       [ 2.,  1.,  2.],
       [ 3.,  3.,  9.],
       [ 4.,  3.,  8.],
       [ 5.,  4., 20.]])

In [7]:
knn_imputer = KNNImputer(n_neighbors = 1)
knn_imputer.fit_transform(my_df)

array([[ 1.,  1.,  1.],
       [ 2.,  1.,  2.],
       [ 3.,  3.,  9.],
       [ 4.,  3.,  9.],
       [ 5.,  4., 20.]])

In [8]:
knn_imputer = KNNImputer(n_neighbors = 2)
knn_imputer.fit_transform(my_df)

array([[ 1. ,  1. ,  1. ],
       [ 2. ,  1. ,  2. ],
       [ 3. ,  3. ,  9. ],
       [ 4. ,  3. , 14.5],
       [ 5. ,  4. , 20. ]])

In [9]:
knn_imputer = KNNImputer(n_neighbors = 2, weights = "distance")
knn_imputer.fit_transform(my_df)

array([[ 1.        ,  1.        ,  1.        ],
       [ 2.        ,  1.        ,  2.        ],
       [ 3.        ,  3.        ,  9.        ],
       [ 4.        ,  3.        , 13.55634919],
       [ 5.        ,  4.        , 20.        ]])